// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Cq1ab5l1YWZQvTci0XxHpxrZezGNpA0',
    appId: '1:857911351350:web:afb9c60424e086d19fe097',
    messagingSenderId: '857911351350',
    projectId: 'caffeapp-zavrsni',
    authDomain: 'caffeapp-zavrsni.firebaseapp.com',
    databaseURL: 'https://caffeapp-zavrsni-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'caffeapp-zavrsni.appspot.com',
    measurementId: 'G-7BKX41TB69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTFg5WXRx-OjBCPcMgR3Pqce3CEXG0-LE',
    appId: '1:857911351350:android:6fe64def271a24c39fe097',
    messagingSenderId: '857911351350',
    projectId: 'caffeapp-zavrsni',
    databaseURL: 'https://caffeapp-zavrsni-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'caffeapp-zavrsni.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPgUkFp4tURHAb02h8zFfSLJlQ_ctn7Q0',
    appId: '1:857911351350:ios:dc599f8745e5730d9fe097',
    messagingSenderId: '857911351350',
    projectId: 'caffeapp-zavrsni',
    databaseURL: 'https://caffeapp-zavrsni-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'caffeapp-zavrsni.appspot.com',
    iosClientId: '857911351350-g05j84kjv8hfntvnklg37nj6gnrsbenu.apps.googleusercontent.com',
    iosBundleId: 'com.example.caffeApp',
  );
}
